---
kind: breeds
name: sava-requester
deployable:
  type: application/javascript
  definition: |
    'use strict';

    let _ = require('highland');
    let vamp = require('vamp-node-client');

    let api = new vamp.Api();
    let http = new vamp.Http();

    var vga;

    var process = function () {
      if (!vga) {
        api.config().each(function (config) {
          vga = config['vamp.gateway-driver.host'];
        });
      } else {
        http.get('http://' + vga + ':9050').then(function (body) {
          var response = JSON.parse(body);
          if (response.id == "runner" && response.port == 8085)
            api.event(['workflows:sava-requester', 'response:ok'], body);
          else
            api.event(['workflows:sava-requester', 'response:failed'], body);
        });
      }
    };

    setInterval(process, 1000);

---
kind: workflows
name: sava-requester
breed: sava-requester
schedule: daemon
environment_variables:
  VAMP_WORKFLOW_EXECUTION_PERIOD:  0
  VAMP_WORKFLOW_EXECUTION_TIMEOUT: 0
