---
kind: breeds
name: sava-requester
deployable:
  type: application/javascript
  definition: |
    'use strict';

    var net = require('net');
    var client = new net.Socket();
    var vamp = require('vamp-node-client');

    var vga;
    var api = new vamp.Api();

    var process = function () {
      if (!vga) {
        api.config().each(function (config) {
          vga = config['vamp.gateway-driver.host'];
        });
      } else {
        client.connect(9057, vga, function() {
          client.write('*');
        });
        client.on('data', function(data) {
          api.event(['workflows:sava-requester', 'response:ok'], JSON.parse(data));
        });
      }
    };

    setInterval(process, 1000);

---
kind: workflows
name: sava-requester
breed: sava-requester
schedule: daemon
environment_variables:
  VAMP_WORKFLOW_EXECUTION_PERIOD:  0
  VAMP_WORKFLOW_EXECUTION_TIMEOUT: 0
