---
kind: breeds
name: runner-requester
deployable:
  type: application/javascript
  definition: |
    'use strict';

    let _ = require('highland');
    let vamp = require('vamp-node-client');

    let api = new vamp.Api();
    let http = new vamp.Http();

    var vga;

    var process = function () {
      if (!vga) {
        api.config().each(function (config) {
          vga = config['vamp.gateway-driver.host'];
        });
      } else {
        http.get('http://' + vga + ':9052/***').then(function (body) {
          var result = JSON.parse(body);
          var result = JSON.parse(body);
          if (result['id'] === 'backend' && result['port'] === 8085 && result['path'] === '***') {
            api.event(['workflows:runner-requester', 'response:ok'], body);
          } else {
            api.event(['workflows:runner-requester', 'response:failed'], body);
          }
        });
      }
    };

    setInterval(process, 1000);

---
kind: workflows
name: runner-requester
breed: runner-requester
schedule: daemon
environment_variables:
  VAMP_WORKFLOW_EXECUTION_PERIOD:  0
  VAMP_WORKFLOW_EXECUTION_TIMEOUT: 0
